//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author xiaoshaoqian
// </auto-generated>
//------------------------------------------------------------------------------
using CTrip.System.Model;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq;

namespace CTrip.System.Interfaces
{
    public interface ISysUserRoleService : IBaseService<Sys_UserRole>
    {

        #region CustomInterface 
        #endregion

    }
}
